# Created with WinGet Releaser v2 using Komac v1.11.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.5.0.schema.json

PackageIdentifier: MartiCliment.UniGetUI
PackageVersion: 3.1.6
PackageLocale: en-US
Publisher: Martí Climent
PublisherUrl: https://github.com/marticliment/UniGetUI
PublisherSupportUrl: https://github.com/marticliment/UniGetUI/issues
Author: Martí Climent
PackageName: UniGetUI (formerly WingetUI)
PackageUrl: https://github.com/marticliment/UniGetUI
License: MIT
LicenseUrl: https://raw.githubusercontent.com/marticliment/UniGetUI/main/LICENSE
Copyright: Copyright (c) 2024 Martí Climent
CopyrightUrl: https://raw.githubusercontent.com/marticliment/UniGetUI/main/LICENSE
ShortDescription: User Interface to install packages from most common CLI package managers such as Winget, Scoop, Chocolatey, Pip, Npm, .NET Tool and PowerShell Gallery.
Description: |-
  The main goal of this project is to give a GUI Store to the most common CLI Package Managers for windows, such as Winget, Scoop, Chocolatey, Pip, Npm, .
  NET Tool and PowerShell Gallery.
  This app allows you to install, remove and maintain up-to-date the packages published on Winget, Scoop, Chocolatey, Pip, Npm, .
  NET Tool and PowerShell Gallery.
Moniker: unigetui
Tags:
- chocolatey
- unigetui
- open-source
- scoop
- scoop-ui
- winget
- winget-ui
- pip
- pip-ui
- microsoft-store
- npm
- npm-ui
- dotnet-tool
- dotnet-tool-ui
- powershell
- powershell-gallery
ReleaseNotes: |-
 Changelog
  - Package operations have been greatly improved:
    - Operations bar can be resized and collapsed
    - Live output and Error dialogs have been improved to prevent dialog flooding
    - Operation notifications have been improved, to prevent notification stacking
    - All operations can be canceled at once,
    - Operations have quick actions associated to them:
      - Retry [for failed operations], Retry as admin, etc.
      - Package details, open install location, etc.
      - Skip this version, ignore updates for this app [for failed updates]
      - Etc.
    - Better queue management + concurrency improvements
    - Much more!
  - Installers can be downloaded from package lists. Download operations will show on the operations bar as well.
  - UniGetUI can now be configured to be fully portable, storing settings on the executable directory.
  - A long-standing issue where WinGet would get corrupted on systems where the user didn't have admin privileges has been finally fixed.
  - UniGetUI now has [optional] telemetry, that will serve to understand how the app is used, (and perhaps help create package rankings in the future)
  - Other fixes and improvements.

 What's Changed
  * Updated Winget Workflows to Newer Versions by @vikingnope in https://github.com/marticliment/UniGetUI/pull/3119
  * Update update-icons.yaml: Don't run for forks by @Saibamen in https://github.com/marticliment/UniGetUI/pull/3139
  * Operations redesign by @marticliment in https://github.com/marticliment/UniGetUI/pull/3070
  * Reorder max operation logs by @mrixner in https://github.com/marticliment/UniGetUI/pull/3155
  * Remove obsolete code by @marticliment in https://github.com/marticliment/UniGetUI/pull/3158
  * Pause Package Updates by @mrixner in https://github.com/marticliment/UniGetUI/pull/3135
  * Skip minor updates by @mrixner in https://github.com/marticliment/UniGetUI/pull/3101
  * Updated username for winget workflow by @vikingnope in https://github.com/marticliment/UniGetUI/pull/3197
  * Diversify Icon Detection (Icons for Steam, Local PC, and Microsoft Store Applications) by @mrixner in https://github.com/marticliment/UniGetUI/pull/3189
  * Better package installer download operations by @marticliment in https://github.com/marticliment/UniGetUI/pull/3178
  * UniGetUI Portable by @marticliment in https://github.com/marticliment/UniGetUI/pull/3203
  * Update icons and screenshots from the excel file by @github-actions in https://github.com/marticliment/UniGetUI/pull/3213
  * Update NuGets by @Saibamen in https://github.com/marticliment/UniGetUI/pull/3216
  * Add (optional) telemetry to UniGetUI by @marticliment in https://github.com/marticliment/UniGetUI/pull/3237
  * Update LangData.py by @thepro-3418 in https://github.com/marticliment/UniGetUI/pull/3244
  * Add Directory.Build.props by @Saibamen in https://github.com/marticliment/UniGetUI/pull/3215
  * Further develop on telemetry by @marticliment in https://github.com/marticliment/UniGetUI/pull/3246
  * Fix WinGet getting corrupted on devices with non-admin accounts by @marticliment in https://github.com/marticliment/UniGetUI/pull/3255
  * Fix warnings part 1 by @Saibamen in https://github.com/marticliment/UniGetUI/pull/3251
  * Load translations from Tolgee by @martinet101 in https://github.com/marticliment/UniGetUI/pull/3257
ReleaseNotesUrl: https://github.com/marticliment/UniGetUI/releases/tag/3.1.6
ManifestType: defaultLocale
ManifestVersion: 1.5.0
